Minor corrections and updates of clarithromycin model, evaluation pla…
Open-Systems-Pharmacology/Clarithromycin-Model pull request #2
Opened 2020-04-14 13:35 UTC by AndreDlm

…n and static content files

2020-04-14 21:26 UTC, Yuri05 commented on Evaluation/Input/evaluation_plan.json
> +    "$schema": "https://github.com/Open-Systems-Pharmacology/QualificationPlan/releases/download/v2.0/OSP_Qualification_Plan_Schema.json",
"$schema": "https://github.com/Open-Systems-Pharmacology/QualificationPlan/releases/download/**v2.0**/
why not 2.1?

2020-04-14 21:28 UTC, Yuri05 commented on Evaluation/Input/evaluation_plan.json
> +            "Path": "https://raw.githubusercontent.com/LMFuhr/Clarithromycin-Model/master/Clarithromycin-Model.json",
Reference to a project outside of OSP???

2020-04-14 21:33 UTC, Yuri05 requested changes
s. comments

2020-04-17 13:43 UTC, sfrechen commented
@Yuri05 
Changes implemented

2020-04-17 13:43 UTC, merged